# Generated by Django 2.2.6 on 2019-11-02 09:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Workers',
            fields=[
                ('id', models.AutoField(db_column='id', primary_key=True, serialize=False)),
                ('firstName', models.CharField(db_column='firstName', max_length=255)),
                ('patronymic', models.CharField(db_column='patronymic', max_length=255)),
                ('lastName', models.CharField(db_column='lastName', max_length=255)),
                ('phone', models.IntegerField(db_column='phone', max_length=11, unique=True)),
            ],
            options={
                'db_table': 'Workers',
            },
        ),
        migrations.CreateModel(
            name='Tasks',
            fields=[
                ('id', models.AutoField(db_column='id', primary_key=True, serialize=False)),
                ('name', models.CharField(db_column='name', max_length=255)),
                ('description', models.CharField(db_column='description', max_length=255)),
                ('deadline', models.DateTimeField(db_column='deadline')),
                ('status', models.BooleanField(db_column='status', default=False)),
                ('address', models.CharField(db_column='address', max_length=255)),
                ('longitude', models.FloatField(db_column='longitude')),
                ('latitude', models.FloatField(db_column='latitude')),
                ('addDateTime', models.DateTimeField(auto_now_add=True, db_column='addDateTime')),
                ('updateDateTime', models.DateTimeField(auto_now=True, db_column='updateDateTime')),
                ('idWorker', models.ForeignKey(db_column='idWorker', on_delete=django.db.models.deletion.DO_NOTHING, to='backend.Workers')),
            ],
            options={
                'db_table': 'Tasks',
            },
        ),
    ]
